<style type="text/css">
.tf  {border-collapse:collapse;border-spacing:0;width:100%}
.tf td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tf th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tf .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.col1 { width: 20%;}
.col2 { width: 80%;}
</style>
<table class="tf">
<thead>
  <tr>
    <th class="tg-0pky col1">Name</th>
    <th class="tg-0pky col2">Vineet Parmar</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky col1">UID No.</td>
    <td class="tg-0pky col2">2021300092</td>
  </tr>
  <tr>
    <td class="tg-0pky col1">Course</td>
    <td class="tg-0pky col2">Advanced Data Visualization</td>
  </tr>
</tbody>
</table>

## <p style="text-align:center;font-weight:500;">Experiment 4</p>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;width:100%}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 10px;word-break:normal;}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top;}
.col1 { width: 20%;}
.col2 { width: 80%;}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky col1">Aim</th>
    <th class="tg-0pky col2">
      Create basic charts using R programming language on dataset Crime or Police / Law and Order
      <br>  
      1. Basic - Bar chart, Pie chart, Histogram, Time line chart, Scatter plot, Bubble plot
      <br>  
      2. Write observations from each chart 
    </th>
  </tr>
</thead>
</table>

### 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np

### 2. Loading Dataset

In [2]:
df = pd.read_csv('../Datasets/crime.csv', encoding='ISO-8859-1')
df.head()

,incident_id,offense_id,offense_code,offense_code_extension,offense_type_id,offense_category_id,first_occurrence_date,last_occurrence_date,reported_date,incident_address,geo_x,geo_y,geo_lon,geo_lat,district_id,precinct_id,neighborhood_id,is_crime,is_traffic,victim_count
0,202268791,202268791299900,2999,0,criminal-mischief-other,public-disorder,2/10/2022 2:50:00 AM,NaN,2/10/2022 3:16:00 AM,1107 N SANTA FE DR,3140929.0,1692612.0,-104.998910,39.733957,1,123,lincoln-park,1,0,1
1,2021387586,2021387586299900,2999,0,criminal-mischief-other,public-disorder,7/7/2021 9:02:00 PM,NaN,7/8/2021 12:55:00 AM,815 16TH ST,3142470.0,1697098.0,-104.993342,39.746248,6,611,cbd,1,0,1
2,2020641486,2020641486299900,2999,0,criminal-mischief-other,public-disorder,10/29/2020 1:30:00 AM,NaN,10/29/2020 4:31:00 AM,4745 N FEDERAL BLVD,3133352.0,1710396.0,-105.025520,39.782888,1,111,berkeley,1,0,1
3,2018612468,2018612468299900,2999,0,criminal-mischief-other,public-disorder,9/6/2018 5:00:00 PM,9/6/2018 11:00:00 PM,9/7/2018 9:58:00 AM,65 S FEDERAL BLVD,3133534.0,1685797.0,-105.025330,39.715357,4,411,barnum,1,0,1
4,2020293614,2020293614299900,2999,0,criminal-mischief-other,public-disorder,5/8/2020 5:00:00 AM,5/8/2020 6:30:00 PM,5/13/2020 10:00:00 AM,12295 E ALBROOK DR,3184065.0,1710782.0,-104.845074,39.783082,5,521,montbello,1,0,1

### 3. Data Preprocessing

In [6]:
df.isnull().sum()

incident_id              0
offense_id               0
offense_code             0
offense_type_id          0
offense_category_id      0
first_occurrence_date    0
reported_date            0
incident_address         0
geo_x                    0
geo_y                    0
district_id              0
neighborhood_id          0
is_crime                 0
is_traffic               0
victim_count             0
dtype: int64

In [4]:
# drop columns: offense_code_extension, last_occurrence_date, geo_lon, geo_lat, precinct_id
df.drop(['offense_code_extension', 'last_occurrence_date', 'geo_lon', 'geo_lat', 'precinct_id'], axis=1, inplace=True)

# drop rows with missing values
df.dropna(inplace=True)

In [5]:
print(df.shape)
df.head()

(370666, 15)

,incident_id,offense_id,offense_code,offense_type_id,offense_category_id,first_occurrence_date,reported_date,incident_address,geo_x,geo_y,district_id,neighborhood_id,is_crime,is_traffic,victim_count
0,202268791,202268791299900,2999,criminal-mischief-other,public-disorder,2/10/2022 2:50:00 AM,2/10/2022 3:16:00 AM,1107 N SANTA FE DR,3140929.0,1692612.0,1,lincoln-park,1,0,1
1,2021387586,2021387586299900,2999,criminal-mischief-other,public-disorder,7/7/2021 9:02:00 PM,7/8/2021 12:55:00 AM,815 16TH ST,3142470.0,1697098.0,6,cbd,1,0,1
2,2020641486,2020641486299900,2999,criminal-mischief-other,public-disorder,10/29/2020 1:30:00 AM,10/29/2020 4:31:00 AM,4745 N FEDERAL BLVD,3133352.0,1710396.0,1,berkeley,1,0,1
3,2018612468,2018612468299900,2999,criminal-mischief-other,public-disorder,9/6/2018 5:00:00 PM,9/7/2018 9:58:00 AM,65 S FEDERAL BLVD,3133534.0,1685797.0,4,barnum,1,0,1
4,2020293614,2020293614299900,2999,criminal-mischief-other,public-disorder,5/8/2020 5:00:00 AM,5/13/2020 10:00:00 AM,12295 E ALBROOK DR,3184065.0,1710782.0,5,montbello,1,0,1

In [10]:
# Save the file with UTF-8 encoding
df.to_csv("../Datasets/crime_cleaned.csv", encoding="utf-8", index=False)

### 4. R Plots
Following plots are created using R:
- **Bar Plot** - To show the Number of crimes per offense category
- **Pie Chart** - To show the distribution of crimes in the dataset
- **Histogram** - To show the victims count by year
- **Scatter Plot** - To show the no. of crimes by neighborhood
- **Bubble Plot** - To show the no. of victims by crime type
- **Timeline Plot** - To show the no. of crimes by year and month

All plots can be found in the Plots Directory.

### 5. Conclusion
In this experiment, I learned how to create different types of plots using R. I have created 6 different plots to visualize the dataset using the ggplot2 library in R. I also used the lubridate library to work with dates. I have created a bar plot, pie chart, histogram, scatter plot, bubble plot, and timeline plot. These plots help us to understand the dataset better and find insights from it.